"""Add audit_context

Revision ID: 500e3559650d
Revises: 88cde83053c3
Create Date: 2026-09-02 10:52:54.056165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500e3559650d'
down_revision: Union[str, None] = '88cde83053c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_events', sa.Column('audit_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_events', 'audit_context')
    # ### end Alembic commands ###
