"""Initial case management tables

Revision ID: 88cde83053c3
Revises: 
Create Date: 2026-09-01 13:55:56.743075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cde83053c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('inference_id', sa.String(), nullable=False),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('reason_codes', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('analyst_note', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_inference_id'), 'cases', ['inference_id'], unique=True)
    op.create_table('case_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('previous_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('case_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_events')
    op.drop_index(op.f('ix_cases_inference_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
