import os
import requests
import json
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

API_URL = os.environ.get("FRAUDSHIELD_API_URL", "http://127.0.0.1:8000/api/v1")
API_KEY = os.environ.get("FRAUDSHIELD_API_KEY", "test_key")

HEADERS = {
    "X-API-Key": API_KEY,
    "Content-Type": "application/json"
}

SYNTHETIC_DATA = [
    {
        "step": 1,
        "type": "TRANSFER",
        "amount": 950000.0,
        "oldbalanceOrg": 950000.0,
        "orig_account_type": "C",
        "dest_account_type": "C"
    },
    {
        "step": 1,
        "type": "PAYMENT",
        "amount": 100.0,
        "oldbalanceOrg": 500.0,
        "orig_account_type": "C",
        "dest_account_type": "M"
    },
    {
        "step": 2,
        "type": "CASH_OUT",
        "amount": 5000.0,
        "oldbalanceOrg": 5000.0,
        "orig_account_type": "C",
        "dest_account_type": "C"
    }
]

def seed_data():
    logger.info("Starting deterministic synthetic data seeding...")
    
    for idx, tx in enumerate(SYNTHETIC_DATA):
        # 1. Predict
        try:
            resp = requests.post(f"{API_URL}/predict", json=tx, headers=HEADERS)
            resp.raise_for_status()
            res_data = resp.json()
            logger.info(f"Predicted TX {idx+1}: Score={res_data['fraud_score']}, Alert={res_data['is_alert']}")
            
            # 2. If it's an alert, we can optionally explicitly create a case, 
            # but the API automatically creates a case when is_alert is true if the DB is connected.
            
            # 3. Add an event to the case if it exists
            # We need to find the case first
            cases_resp = requests.get(f"{API_URL}/cases?status=OPEN", headers=HEADERS)
            if cases_resp.status_code == 200:
                cases = cases_resp.json().get("items", [])
                for c in cases:
                    if c["inference_id"] == res_data["inference_id"]:
                        # Add a demo comment
                        comment_data = {
                            "event_type": "COMMENT",
                            "analyst_id": "demo_script",
                            "comment": "Synthetic transaction generated by seed script."
                        }
                        requests.post(f"{API_URL}/cases/{c['id']}/events", json=comment_data, headers=HEADERS)
                        logger.info(f"Added comment to case {c['id']}")
                        
        except Exception as e:
            logger.error(f"Failed to process TX {idx+1}: {e}")
            
    logger.info("Seeding complete.")

if __name__ == "__main__":
    seed_data()
